//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: AppFrameBase.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#include "AppFrameBase.h"


// Declare the bitmap loading function
extern void wxC2843InitBitmapResources();

static bool bBitmapLoaded = false;


AppFrameBase::AppFrameBase(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style)
    : wxDialog(parent, id, title, pos, size, style)
{
    if ( !bBitmapLoaded ) {
        // We need to initialise the default bitmap handler
        wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
        wxC2843InitBitmapResources();
        bBitmapLoaded = true;
    }
    
    main_sizer = new wxBoxSizer(wxVERTICAL);
    this->SetSizer(main_sizer);
    
    boxSizer110 = new wxBoxSizer(wxHORIZONTAL);
    
    main_sizer->Add(boxSizer110, 0, wxALL|wxEXPAND, WXC_FROM_DIP(5));
    
    boxSizer110->Add(0, 0, 1, wxALL, WXC_FROM_DIP(5));
    
    gridSizer100 = new wxGridSizer(0, 2, 0, 0);
    
    boxSizer110->Add(gridSizer100, 0, wxALL|wxEXPAND, WXC_FROM_DIP(5));
    
    CCT = new wxTextCtrl(this, wxID_ANY, wxT("Current Session"), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), wxTE_READONLY|wxBORDER_SIMPLE);
    #if wxVERSION_NUMBER >= 3000
    CCT->SetHint(wxT(""));
    #endif
    
    gridSizer100->Add(CCT, 0, wxALL, WXC_FROM_DIP(5));
    CCT->SetMinSize(wxSize(200,-1));
    
    CurrentConnectTime = new wxTextCtrl(this, wxID_ANY, wxT(""), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), wxTE_READONLY|wxTE_CENTRE|wxBORDER_SIMPLE);
    #if wxVERSION_NUMBER >= 3000
    CurrentConnectTime->SetHint(wxT(""));
    #endif
    
    gridSizer100->Add(CurrentConnectTime, 0, wxALL, WXC_FROM_DIP(5));
    CurrentConnectTime->SetMinSize(wxSize(200,-1));
    
    CU = new wxTextCtrl(this, wxID_ANY, wxT("Current Up"), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), wxTE_READONLY|wxBORDER_SIMPLE);
    #if wxVERSION_NUMBER >= 3000
    CU->SetHint(wxT(""));
    #endif
    
    gridSizer100->Add(CU, 0, wxALL, WXC_FROM_DIP(5));
    CU->SetMinSize(wxSize(200,-1));
    
    CurrentUpload = new wxTextCtrl(this, wxID_ANY, wxT(""), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), wxTE_READONLY|wxTE_CENTRE|wxBORDER_SIMPLE);
    #if wxVERSION_NUMBER >= 3000
    CurrentUpload->SetHint(wxT(""));
    #endif
    
    gridSizer100->Add(CurrentUpload, 0, wxALL, WXC_FROM_DIP(5));
    CurrentUpload->SetMinSize(wxSize(200,-1));
    
    CD = new wxTextCtrl(this, wxID_ANY, wxT("Current Down"), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), wxTE_READONLY|wxBORDER_SIMPLE);
    #if wxVERSION_NUMBER >= 3000
    CD->SetHint(wxT(""));
    #endif
    
    gridSizer100->Add(CD, 0, wxALL, WXC_FROM_DIP(5));
    CD->SetMinSize(wxSize(200,-1));
    
    CurrentDownload = new wxTextCtrl(this, wxID_ANY, wxT(""), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), wxTE_READONLY|wxTE_CENTRE|wxBORDER_SIMPLE);
    #if wxVERSION_NUMBER >= 3000
    CurrentDownload->SetHint(wxT(""));
    #endif
    
    gridSizer100->Add(CurrentDownload, 0, wxALL, WXC_FROM_DIP(5));
    CurrentDownload->SetMinSize(wxSize(200,-1));
    
    TU = new wxTextCtrl(this, wxID_ANY, wxT("Total Up"), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), wxTE_READONLY|wxBORDER_SIMPLE);
    #if wxVERSION_NUMBER >= 3000
    TU->SetHint(wxT(""));
    #endif
    
    gridSizer100->Add(TU, 0, wxALL, WXC_FROM_DIP(5));
    TU->SetMinSize(wxSize(200,-1));
    
    TotalUpload = new wxTextCtrl(this, wxID_ANY, wxT(""), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), wxTE_READONLY|wxTE_CENTRE|wxBORDER_SIMPLE);
    #if wxVERSION_NUMBER >= 3000
    TotalUpload->SetHint(wxT(""));
    #endif
    
    gridSizer100->Add(TotalUpload, 0, wxALL, WXC_FROM_DIP(5));
    TotalUpload->SetMinSize(wxSize(200,-1));
    
    TD = new wxTextCtrl(this, wxID_ANY, wxT("Total Down"), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), wxTE_READONLY|wxBORDER_SIMPLE);
    #if wxVERSION_NUMBER >= 3000
    TD->SetHint(wxT(""));
    #endif
    
    gridSizer100->Add(TD, 0, wxALL, WXC_FROM_DIP(5));
    TD->SetMinSize(wxSize(200,-1));
    
    TotalDownload = new wxTextCtrl(this, wxID_ANY, wxT(""), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), wxTE_READONLY|wxTE_CENTRE|wxBORDER_SIMPLE);
    #if wxVERSION_NUMBER >= 3000
    TotalDownload->SetHint(wxT(""));
    #endif
    
    gridSizer100->Add(TotalDownload, 0, wxALL, WXC_FROM_DIP(5));
    TotalDownload->SetMinSize(wxSize(200,-1));
    
    TUD = new wxTextCtrl(this, wxID_ANY, wxT("Total (Up + Down)"), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), wxTE_READONLY|wxBORDER_SIMPLE);
    #if wxVERSION_NUMBER >= 3000
    TUD->SetHint(wxT(""));
    #endif
    
    gridSizer100->Add(TUD, 0, wxALL, WXC_FROM_DIP(5));
    TUD->SetMinSize(wxSize(200,-1));
    
    TotalUploadDownload = new wxTextCtrl(this, wxID_ANY, wxT(""), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), wxTE_READONLY|wxTE_CENTRE|wxBORDER_SIMPLE);
    #if wxVERSION_NUMBER >= 3000
    TotalUploadDownload->SetHint(wxT(""));
    #endif
    
    gridSizer100->Add(TotalUploadDownload, 0, wxALL, WXC_FROM_DIP(5));
    TotalUploadDownload->SetMinSize(wxSize(200,-1));
    
    TCT = new wxTextCtrl(this, wxID_ANY, wxT("Total Sessions"), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), wxTE_READONLY|wxBORDER_SIMPLE);
    #if wxVERSION_NUMBER >= 3000
    TCT->SetHint(wxT(""));
    #endif
    
    gridSizer100->Add(TCT, 0, wxALL, WXC_FROM_DIP(5));
    TCT->SetMinSize(wxSize(200,-1));
    
    TotalConnectTime = new wxTextCtrl(this, wxID_ANY, wxT(""), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), wxTE_READONLY|wxTE_CENTRE|wxBORDER_SIMPLE);
    #if wxVERSION_NUMBER >= 3000
    TotalConnectTime->SetHint(wxT(""));
    #endif
    
    gridSizer100->Add(TotalConnectTime, 0, wxALL, WXC_FROM_DIP(5));
    TotalConnectTime->SetMinSize(wxSize(200,-1));
    
    boxSizer110->Add(0, 0, 1, wxALL, WXC_FROM_DIP(5));
    
    m_pBackgroundTimer = new wxTimer;
    
    SetName(wxT("AppFrameBase"));
    SetMinClientSize(wxSize(300,-1));
    SetSize(wxDLG_UNIT(this, wxSize(-1,-1)));
    if (GetSizer()) {
         GetSizer()->Fit(this);
    }
    if(GetParent()) {
        CentreOnParent(wxBOTH);
    } else {
        CentreOnScreen(wxBOTH);
    }
    // Connect events
    this->Connect(wxEVT_CLOSE_WINDOW, wxCloseEventHandler(AppFrameBase::OnClose), NULL, this);
    m_pBackgroundTimer->Connect(wxEVT_TIMER, wxTimerEventHandler(AppFrameBase::OnBackgroundTimer), NULL, this);
    
}

AppFrameBase::~AppFrameBase()
{
    this->Disconnect(wxEVT_CLOSE_WINDOW, wxCloseEventHandler(AppFrameBase::OnClose), NULL, this);
    m_pBackgroundTimer->Disconnect(wxEVT_TIMER, wxTimerEventHandler(AppFrameBase::OnBackgroundTimer), NULL, this);
    
    m_pBackgroundTimer->Stop();
    wxDELETE( m_pBackgroundTimer );

}
